<a href="https://colab.research.google.com/github/1998456/Doc.Daves-Portfolio-/blob/main/Daves(pond)DF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split

In [18]:
r1= pd.Series({'Cycle':1,
               'Feed_Amount':318452,
               'Income':340000,
               'Expenses':288950,
               'Casualties':20,
               'Total_Wt_gain':365053,
               'Harvest':1080,
               'Profit':'Yes'})
r1

Cycle                 1
Feed_Amount      318452
Income           340000
Expenses         288950
Casualties           20
Total_Wt_gain    365053
Harvest            1080
Profit              Yes
dtype: object

In [3]:
r2= pd.Series({'Cycle':2,
               'Feed_Amount':253450,
               'Income':206400,
               'Expenses':274100,
               'Casualties':73,
               'Total_Wt_gain':271720,
               'Harvest':1027,
               'Profit':'No'})
r2

Cycle                 2
Feed_Amount      253450
Income           206400
Expenses         274100
Casualties           73
Total_Wt_gain    271720
Harvest            1027
Profit               No
dtype: object

In [4]:
r3= pd.Series({'Cycle':3,
               'Feed_Amount':208720,
               'Income':258000,
               'Expenses':488580,
               'Casualties':60,
               'Total_Wt_gain':344600,
               'Harvest':960,
               'Profit':'No'})
r3

Cycle                 3
Feed_Amount      208720
Income           258000
Expenses         488580
Casualties           60
Total_Wt_gain    344600
Harvest             960
Profit               No
dtype: object

In [5]:
df= pd.DataFrame([r1,r2,r3])
df

Cycle  Feed_Amount  Income  Expenses  Casualties  Total_Wt_gain  Harvest  \
0      1       318452  340000    288950          20         365053     1080   
1      2       253450  206400    274100          73         271720     1027   
2      3       208720  258000    488580          60         344600      960   

  Profit  
0    Yes  
1     No  
2     No

In [19]:
x= df.iloc[:,:-1].values
y= df.iloc[:7].values

In [20]:
x

array([[     1, 318452, 340000, 288950,     20, 365053,   1080],
       [     2, 253450, 206400, 274100,     73, 271720,   1027],
       [     3, 208720, 258000, 488580,     60, 344600,    960]])

In [21]:
y

array([[1, 318452, 340000, 288950, 20, 365053, 1080, 'Yes'],
       [2, 253450, 206400, 274100, 73, 271720, 1027, 'No'],
       [3, 208720, 258000, 488580, 60, 344600, 960, 'No']], dtype=object)

In [33]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_y= LabelEncoder()
y[:,7]= labelencoder_y.fit_transform(y[:,7])
ct= ColumnTransformer([('Profit',OneHotEncoder(),[7])])
y= ct.fit_transform(y)

In [34]:
y=y[:,1:]

In [35]:
y

array([[1.],
       [0.],
       [0.]])

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=100)

In [37]:
x_train

array([[     3, 208720, 258000, 488580,     60, 344600,      0],
       [     1, 318452, 340000, 288950,     20, 365053,      2]])

In [38]:
x_test

array([[     2, 253450, 206400, 274100,     73, 271720,      1]])

In [40]:
from sklearn.linear_model import LinearRegression
LR= LinearRegression ()
LR.fit(x_train,y_train)

LinearRegression()

In [41]:
y_lr_test_pred= LR.predict(x_test)

In [42]:
y_lr_test_pred

array([[0.71148861]])

In [43]:
LR.coef_

array([[-3.38778776e-11,  1.85874363e-06,  1.38899298e-06,
        -3.38152035e-06, -6.77557551e-10,  3.46452115e-07,
         3.38778776e-11]])

In [44]:
LR.intercept_

array([0.78643869])

In [46]:
from sklearn.metrics import r2_score
r2_score(y_test,y_lr_test_pred)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:918: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


nan